language: ruby
rvm:
  - 2.6.0

addons:
  chrome: "stable"

before_install:
  - cp config/database.example.yml config/database.yml
  - cp sample.env .env
  - bundle install
  - bundle exec rails db:create
  - bundle exec rails db:migrate

script:
  - bundle exec rails test
