version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "bundle exec rails db:create
      && bundle exec rails db:migrate
      && bundle exec rails s"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
