development:
  adapter: postgresql
  encoding: unicode
  database: chewie_development
  pool: 5
  username: postgres
  password: postgres
  url: <%= ENV['DATABASE_URL'] %>
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: chewie_test
  pool: 5
  username: postgres
  password: postgres
  url: <%= ENV['DATABASE_URL'] %>
  host: localhost
