Customer.create!(name: 'Darth ​Vader')
Customer.create!(name: 'Obi-Wan ​Kenobi')
Customer.create!(name: 'Luke ​Skywalker')
Customer.create!(name: 'Imperador ​Palpatine')
Customer.create!(name: 'Han ​Solo')
